title: Baihua's Blog
name: "Baihua's Machine Learning Blog"
author: Baihua Xie
baseurl: "/"
description: Blogs on my learning
profile_url: "http://baihuaxie.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Build settings
theme: minima